import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";

import { auth } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/providers/query-providers";
import { Navbar } from "@/components/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: ["700", "900"],
});

export const metadata: Metadata = {
  title: "Agenda West 4",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased bg-main-image`}
        >
          <QueryProvider>
            <Navbar />
            {children}
            <Toaster richColors />
          </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
